# Generated by Django 2.2.5 on 2019-09-15 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0002_auto_20190914_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='avg_procedure_cost',
        ),
        migrations.RemoveField(
            model_name='country',
            name='avg_waiting_time',
        ),
        migrations.RemoveField(
            model_name='country',
            name='hospital_1',
        ),
        migrations.RemoveField(
            model_name='country',
            name='hospital_2',
        ),
        migrations.RemoveField(
            model_name='country',
            name='hospital_3',
        ),
        migrations.AddField(
            model_name='country',
            name='avg_per_night_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='city',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='hospital_1_link',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='hospital_1_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='hospital_2_link',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='hospital_2_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='hospital_3_link',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='hospital_3_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='quality_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('avg_procedure_cost', models.IntegerField(default=0)),
                ('avg_waiting_time', models.IntegerField(default=0)),
                ('avg_recovery_time', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='searches.Country')),
            ],
        ),
    ]
