# Generated by Django 2.2.5 on 2019-09-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0003_auto_20190915_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
